vich_uploader:
    db_driver: orm

    mappings:
        property_image:                                         # on l'appelle par exemple property_image
            uri_prefix:   '%app.path.property_image%'                      # dossier ou l'image serra envoyée
            upload_destination: '%kernel.project_dir%/public/%app.path.property_image%'

        property_work:                                         # on l'appelle par exemple property_image
            uri_prefix:   '%app.path.property_work%'                      # dossier ou l'image serra envoyée
            upload_destination: '%kernel.project_dir%/public/%app.path.property_work%'
